networks:
    internal:

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
          - "8080:80"
        volumes:
          - $PWD:/var/www
          - ./docker/nginx:/etc/nginx/conf.d
          - ./logs/nginx:/var/log/nginx
        depends_on:
          - phpfpm
        networks:
          - internal

    phpfpm:
        build:
          context: ./docker/phpfpm
          dockerfile: Dockerfile
        container_name: phpfpm
        volumes:
          - $PWD:/var/www
          - ./docker/phpfpm:/usr/local/etc/php/php.ini
        ports:
          - "9000:9000"
        networks:
          - internal